language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t mshea/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mshea/docker-react npm run test
      