language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t IMAGE_TO_TEST -f Dockerfile.dev .

script:
    - docker run -e CI=true IMAGE_TO_TEST npm run test
      